# -*- coding: utf-8 -*-
"""Making the Most of your Colab Subscription

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/pro.ipynb
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Use correct file name
df = pd.read_csv("titanic_taks5_raw.csv")

df.head()
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

# ==============================
# STEP 5: Data Cleaning
# ==============================

# Fill Age missing values with median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Fill Embarked missing values with most frequent value
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Drop Cabin column (too many missing values)
df.drop(columns=['Cabin'], inplace=True)

# ==============================
# STEP 6: Survival Count
# ==============================
plt.figure()
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

# ==============================
# STEP 7: Survival by Gender
# ==============================
plt.figure()
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()

# ==============================
# STEP 8: Survival by Passenger Class
# ==============================
plt.figure()
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()

# ==============================
# STEP 9: Age Distribution
# ==============================
plt.figure()
sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

# ==============================
# STEP 10: Correlation Heatmap
# ==============================
plt.figure()
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

print("\nAnalysis Completed Successfully ✅")